[package]
name = "mesh_to_vox"
version = "0.1.1"
edition = "2024"
repository = "https://github.com/szostid/MeshToVox"
keywords = ["glTF", "3D", "cli"]
description = "A program to convert triangle meshes to voxels."

[dependencies]
image = { version = "0.25.1" }
gltf = { version = "1.4.1", default-features = false, features = [
    "import",
    "utils",
    "KHR_materials_pbrSpecularGlossiness",
] }
json = { version = "0.12.4", default-features = false }
clap = { version = "4.5.4", features = ["derive"] }
glam = { version = "0.30.9", features = ["bytemuck"] }
bytemuck = "1.24.0"
anyhow = "1.0.100"
rayon = "1.11.0"
profiling = { version = "1.0.17", features = ["profile-with-tracy"] }
tracy-client = "0.18.2"
dot_vox = "5.1.1"
